# Application name
spring:
  application:
    name: authentication_Service

  # DataSource configuration for MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/authentication_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: update # Automatically update the schema
    show-sql: true # Show SQL queries in the logs
    properties:
      hibernate:
        format_sql: true # Format SQL queries for better readability
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL dialect for Hibernate

  # Mail configuration (if needed)
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Server configuration
server:
  port: 8080 # Port on which the application will run

# Logging configuration (optional)
logging:
  level:
    org:
      hibernate: INFO # Set Hibernate logging level
    root: INFO # Set root logging level